[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
sourceSets.main.resources.srcDirs += [ rootProject.file('assets').path ]
eclipse.project.name = appName + '-core'

dependencies {
  api "com.badlogicgames.gdx:gdx-ai:$aiVersion"
  api "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
  api "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  
  implementation 'com.github.crykn:kryonet:2.22.9'
  implementation "com.badlogicgames.gdx:gdx-backend-headless:$gdxVersion"

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}

task copyAssets(type: Copy) {
    from '../../assets'
    into 'src/main/resources'
}
processResources.dependsOn copyAssets
